#!/bin/bash
#SBATCH -p normal
#SBATCH -c 16

in=$1
out=$2

/home/mathiser/faststorage/applications/ont-guppy-cpu/bin/guppy_basecaller -r --kit SQK-RPB004 --flowcell FLO-MIN106 -t 32 -i $in -s $out

for file in $(find $out -name "*.fastq")
do
    echo $file
    echo "In: "$in;
    echo "Out: "$out;
    chopfile="${file%.*}_porechopped.fastq"
    echo "Rawfile: "$file
    echo "Chopfile: "$chopfile
    porechop -i $file -o $chopfile
done