#!/bin/bash
#SBATCH -p normal
#SBATCH -c 32

SECONDS=0
source activate unipipe
dr=$(dirname $1)
filename_with_suffix=$(basename -- "$1")
filename=${filename_with_suffix%.*}
basefol=$dr/APOMMIR/$filename
trimmed_fastq=$1
paths=$basefol/filepaths.txt

echo "Basefol: "$basefol

echo '0 Mapping overlaps ...'
mkdir -p $basefol/0/
echo '0_minimap_start='$SECONDS >> $paths
minimap2 -x ava-ont $trimmed_fastq $trimmed_fastq > $basefol/0/overlaps.paf
echo '0_miniasm_start='$SECONDS >> $paths
echo '0 Assembling ...'
miniasm -f $trimmed_fastq $basefol/0/overlaps.paf > $basefol/0/assembly.gfa
awk '/^S/{print ">"$2"\n"$3}' $basefol/0/assembly.gfa | fold > $basefol/0/assembly.fasta
echo realpath $basefol/0/assembly.fasta >> $paths


counter=1
while [ $counter -lt 4 ]
do
mkdir -p $basefol/$counter
echo $counter' Mapping ...'
echo $counter'_minimap_start='$SECONDS >> $paths
minimap2 -x ava-ont $basefol/$(expr $counter - 1)/assembly.fasta $trimmed_fastq > $basefol/$counter/overlaps.paf
echo $counter' Polishing ...'
echo $counter'_racon_start='$SECONDS >> $paths
racon $trimmed_fastq $basefol/$counter/overlaps.paf $basefol/$(expr $counter - 1)/assembly.fasta > $basefol/$counter/assembly.fasta
echo realpath $basefol/$counter/assembly.fasta >> $paths
echo $counter'_racon_end='$SECONDS >> $paths

counter=$[$counter+1]
done


echo "Done in: "$SECONDS" seconds"
echo 'done='$SECONDS >> $paths
DATE=`date '+%Y%m%d%H%M'`
echo 'DATE='$DATE >> $paths