#!/bin/bash
#SBATCH -p normal
#SBATCH -c 32

SECONDS=0
FQ=$1
dr=$(dirname $1)
filename_with_suffix=$(basename -- "$1")
filename=${filename_with_suffix%.*}
basefol=$dr/$filename
porechopped=$basefol/porechop
unicycled=$basefol/unicycled

echo $basefol
mkdir -p $porechopped
mkdir -p $unicycled

echo 'Chopping: '$FQ
trimmed_fastq=$porechopped/trimmed_$filename_with_suffix
echo $trimmed_fastq

porechop -i $FQ -o $trimmed_fastq
wait

unicycler -l $trimmed_fastq -o $unicycled

wait
echo "Done in: "$SECONDS" seconds"