#!/bin/bash
#SBATCH -p normal
#SBATCH -c 32
SBATCH --mem-per-cpu 8

SECONDS=0

dr=$(dirname $1)
filename_with_suffix=$(basename -- "$1")
filename=${filename_with_suffix%.*}
basefol=$dr/APUNI/$filename
trimmed_fastq=$1
paths=$basefol/filepaths.txt
unicycled=$basefol/unicycled

mkdir -p $unicycled

echo "Basefol: "$basefol


echo 'Unicycling ...'
'unicycler_start='$SECONDS >> $paths
unicycler -t 32 -l $trimmed_fastq -o $unicycled


echo "Done in: "$SECONDS" seconds"
'SECS='$SECONDS >> $paths
DATE=`date '+%Y%m%d%H%M'`
'DATE='$DATE >> $paths