#!/bin/bash
#SBATCH -p normal
#SBATCH -c 32

DIR=$(dirname $1)
filename=$(basename -- "$1")
filename="$DIR/${filename%.*}.paf"
echo $filename

ref="/home/mathiser/faststorage/ref/SpeciesTyping/Bacteria/genomeDB.fasta"
minimap2="/home/mathiser/faststorage/applications/minimap2-2.15_x64-linux/minimap2"

$minimap2 -cs $ref $1 > $filename