#!/bin/bash
#SBATCH -p normal
#SBATCH -c 16

in=$1
out=$2
source activate albacore2.34
read_fast5_basecaller.py -r -k SQK-RPB004 -f FLO-MIN106 --barcoding -t 32 -i $in -s $out

for file in $(find $out -name "*.fastq")
do
    echo $file
    echo "In: "$in;
    echo "Out: "$out;
    chopfile="${file%.*}_porechopped.fastq"
    echo "Rawfile: "$file
    echo "Chopfile: "$chopfile
    porechop -i $file -o $chopfile
done