#!/bin/bash
#SBATCH -p normal
#SBATCH -c 32

SECONDS=0
FQ=$1
DIR=$(dirname $1)
FNWS=$(basename -- "$1")
FNWOS=${FNWS%.*}
BASEFOL=$DIR/$FNWOS
PORECHOP_FOL=$BASEFOL/porechop
CANU_LVL1=$BASEFOL'/canu1/'
CANU_LVL2=$BASEFOL'/canu2/'
CANU_LVL3=$BASEFOL'/canu3/'
CANU_LVL4=$BASEFOL'/canu4/'


mkdir -p $PORECHOP_FOL
TRIMMED_FASTQ=$PORECHOP_FOL/porechoped_$FNWS
echo $TRIMMED_FASTQ

porechop -i $FQ -o $TRIMMED_FASTQ
wait

/home/mathiser/faststorage/applications/canu-1.8/Linux-amd64/bin/canu -p $FNWOS -d $CANU_LVL4 genomeSize=4.8m -nanopore-raw $TRIMMED_FASTQ &
%/home/mathiser/faststorage/applications/canu-1.8/Linux-amd64/bin/canu -p $FNWOS -d $CANU_LVL3 genomeSize=4.8m correctedErrorRate=0.105 -nanopore-raw $TRIMMED_FASTQ &
%/home/mathiser/faststorage/applications/canu-1.8/Linux-amd64/bin/canu -p $FNWOS -d $CANU_LVL2 genomeSize=1m -nanopore-raw $TRIMMED_FASTQ &
/home/mathiser/faststorage/applications/canu-1.8/Linux-amd64/bin/canu -p $FNWOS -d $CANU_LVL1 genomeSize=1m correctedErrorRate=0.105 -nanopore-raw $TRIMMED_FASTQ &
wait
echo "Done in: "$SECONDS" seconds"